### ISSUE TITLE
Name the sponsor for the first versions in the README

### ISSUE THREAD

**Issue by kelson42** [offspot/metrics#115]
With the logo and link to https://www.hirschmann-stiftung.ch/

**Comment by benoit74** [comment]
@kelson42 are you going to do this?

Otherwise I probably need you to be more specific about which exact text you want to display in the README and which logo is appropriate (or just tell you don't care)

**Comment by Popolechien** [comment]
@benoit74 How about "Development of this tool was made possible through a grant from the Hirschmann Stiftung". Logo I'm not sure we need but you can use this one here: https://kiwix.org/wp-content/uploads/2023/07/logo_hirschmann_stiftung-1.jpg

**Comment by benoit74** [comment]
Will do!

**Comment by HimaTeju** [comment]
@kelson42 Can I work on this?

**Comment by Popolechien** [comment]
@HimaTeju Low hanging fruit. go fo it.
