### ISSUE TITLE
Include a better system description on the home page

### ISSUE THREAD

**Issue by benoit74** [offspot/metrics#12]
Current project description on the home page is too technical.

We need to include more statements about the mission of the project rather than technical details (e.g. reverse proxy logs).

Any suggestion is more than welcomed.

**Comment by benoit74** [comment]
@Popolechien @kelson42 
Do you have any suggestion to make the introduction on https://github.com/offspot/metrics/blob/main/README.md more clear / appealing or do we live with it for now?

**Comment by Popolechien** [comment]
I'll know it when I use it, but I'd say that for the time being we're good. Maybe add a screenshot when we have one so people know what they'll get.
