### ISSUE TITLE
Backend: Make log level live-updatable

### ISSUE THREAD

**Issue by benoit74** [offspot/metrics#21]
Log level (INFO/DEBUG/...) should be set based on an environment variable.

This level should be refreshed every minute or so, so that we can change it without having to restart the server.

**Comment by benoit74** [comment]
Environment variables cannot be updated once a process is started.

The correct need is: as a power user, I want to be able to update log level (INFO/DEBUG/...) live, i.e. I can change it without having to restart the server.

**Comment by rgaudin** [comment]
Is there a need for changing it live or is it just to save some commands? What's the use case where you dont want to restart the service?

**Comment by benoit74** [comment]
I honestly don't know.
I find this would be useful for less technical persons on the field to only alter the configuration.
But maybe there is no "less-technical" persons, it is either us or non-technical persons.

**Comment by rgaudin** [comment]
At the moment, we just cannot support anything beyond expected usage (ie. non-technical). If one has the skills, one can anything (it's their hardware and free software) but maintenance scope just becomes incredibly larger when you target those usages. I don't think that's worth the effort. Decent READMEs (as you do) in all the repos really makes a difference though and it both helps those techie users and ourselves.
