### ISSUE TITLE
Dev: use offspot kiwix-serve image instead of kiwix one

### ISSUE THREAD

**Issue by benoit74** [offspot/metrics#24]
We must switch the `dev` docker-compose `kiwix-serve` image from `ghcr.io/kiwix/kiwix-serve` to ` ghcr.io/offspot/kiwix-serve` to use the same one that will be used on the `offspot`.

When I tried this (beware that we must use a specific version, `latest` and `dev` tags are not maintained anymore), I first realized that `*.zim` as a command did not worked anymore. I tried to pass the exact list of ZIMs, and then I get this error:
```
[dumb-init] /data/devops.stackexchange.com_en_all_2023-05.zim: Permission denied
```

**Comment by rgaudin** [comment]
It's a _pure_ container with no magic entrypoint.

```Dockerfile
  command: ["kiwix-serve", "/data/xxx.zim", "/data/yyy.zim"]
```

**Comment by benoit74** [comment]
OK, my bad ...
Fixed by https://github.com/offspot/metrics/commit/deb3539967c2a57bde085e05be4027b64108c4d7
