### ISSUE TITLE
Backend is incredibly slow to serve HTTP requests when processing is enabled

### ISSUE THREAD

**Issue by rgaudin** [offspot/metrics#78]
First request to metrics home **takes just under a minute** to display… when served on my laptop. It's even longer on the Pi.
Refreshing the page takes about 30s.
All of this is on a fresh, empty database.

The reload delay might be partly due to the fact that nothing's cached in the browser since there's no webserver doing it and it's not implemented in the code 🤓

Might be due to a configuration issue though…

```sh
docker run \
  -v $PWD/mounts/data:/data 
  -v $PWD/mounts/conf:/conf 
  -v $PWD/mounts/log:/var/log/metrics \
  -e ALLOWED_ORIGINS=http://localhost \
  -e PACKAGE_CONF_FILE=/conf/packages.yaml \
  -e "DATABASE_URL=sqlite+pysqlite:////data/database.db" \
  -e LOGWATCHER_DATA_FOLDER=/data/logwatcher \
  -e REVERSE_PROXY_LOGS_LOCATION=/var/log/metrics \
  --rm -it --name metrics \
  -p 80:80 \
  ghcr.io/offspot/metrics:dev
```

**Comment by benoit74** [comment]
This is extremely weird because these files are already compiled by Vite, they are just static files.
Let's have a look, maybe we will need this proxy in front in the end ^^

**Comment by benoit74** [comment]
Issue disappears if you set `PROCESSING_DISABLED="True"` environment variable. This is why I did not catched this before. But this is not really the purpose of metrics 🤣

**Comment by rgaudin** [comment]
Indeed 😅
