### ISSUE TITLE
Decide which KPIs will be included in v1

### ISSUE THREAD

**Issue by benoit74** [offspot/metrics#8]
🚧 This is the list of KPI to include in metrics v1. This is a WIP for now. 🚧

Reminder: in v1, all KPIs are kept at daily, weekly, monthly and yearly aggregations, meaning it is possible to compare one day with the previous ones, one week with the previous ones, etc ...

| Identifier | Display name | Definition |
|----------|----------|----------|
| content_popularity | Content popularity | Number of visits of each content home pages, list sorted descending, limited to 5 on default display, absolute value and percentage available |
| content_object_popularity | Resource popularity | Number of visits per resources and contents, ignored assets (images, technical files like CSS, JS, ...), implemented only for ZIMs in v1, list sorted descending, limited to 10 on default display, absolute value and percentage available
| operation_duration | Operation duration | Duration during which the offspot has been turned on, single value, absolute value and percentage of the whole period available |
| content_usage_duration | Content usage duration | Duration during which a given content has been used, based on 10 minutes interval (i.e. a single activity during a 10 minutes interval is marking these 10 minutes as "active"), list sorted descending, limited to 5 on default display, absolute value and percentage available |
| edupi_files_added | Number of files added to EduPi | Number of files added to EduPi, single value |
| edupi_files_removed | Number of files removed from EduPi | Number of files removed from EduPi, single value |

**Comment by benoit74** [comment]
What I found that has been mentionned already :

- In the [EPIC ticket ](https://github.com/offspot/metrics/issues/1):
  - Content popularity (Sorted nb of hits to home url of each content) => covered by `content_popularity`
  - Top 50 most accessed pages (Sorted nb of hits inside content, resources (css/js/fonts/etc) excluded) => covered by `content_object_popularity`

- In https://github.com/offspot/kiwix-hotspot/issues/541 :
  -  number of different devices => not feasible for v1, we won't aggregate data across offspots
  -  contents (zim files) being accessed, incl. relative "popularity" (ie how many times each content has been accessed) => covered by `content_popularity`

- In https://github.com/offspot/kiwix-hotspot/issues/612 :
  - Something to track URL changes / searches => covered by `content_popularity`  

- In https://github.com/offspot/metrics/issues/5 :
   - Duration of operation for the device => covered by `operation_duration`
   - Duration of use for each zim file => covered by `content_usage_duration`
   - Number of files added/deleted (via EduPi presumably) => covered by `edupi_files_added` and `edupi_files_removed`

Implementation details :
- `content_popularity`, `convent_object_popularity` and `content_usage_duration` will be based on Caddy logs + interpretation based on configuration ("`packages.yml`" file)
- `operation_duration` will be based on the uptime of the `metrics` service (assuming it is almost equal to the offspot uptime
- `edupi_files_added` and `edupi_files_removed` will be subject to https://github.com/offspot/metrics/issues/10

@rgaudin @kelson42 @Popolechien did I missed / misinterpreted something ? Is it sufficient for you for the V1 ?

**Comment by rgaudin** [comment]
Works for me 👍

**Comment by rgaudin** [comment]
> Is there a way to track the number of unique devices that connected to the Pi? Min / Max number of simultaneous users?

We could but that's clearly outside the v1 scope to me.

I am not questioning the usefulness (seems obvious) but it requires a lot of external work. I would thus suggest you open a separate ticket that we'll assign for v2

**Comment by Popolechien** [comment]
Ah yes another question / metrics idea that arose during our discussion today was indicating the age / version / release date of the Pi (as well as its content selection).

**Comment by rgaudin** [comment]
> Ah yes another question / metrics idea that arose during our discussion today was indicating the age / version / release date of the Pi (as well as its content selection).

This serves a different purpose and only works at another level. So not a metrics KPI but we may want to collect the indicators… We should probably move this to a dedicated ticket as well 😉

**Comment by benoit74** [comment]
I suggest this as the final list of KPIs that will be included in metrics v1.

Reminder: in v1, all KPIs are kept at daily, weekly, monthly and yearly aggregations, meaning it is possible to compare one day with the previous ones, one week with the previous ones, etc ...

| Name | Unique ID | Definition |
|----------|----------|----------|
| ContentPopularity | 2001 | Number of visits of each content home pages, list of top 10 stored in DB, absolute value and percentage available |
| ContentObjectPopularity | 2002 | Number of visits per resources and contents, ignoring assets (images, technical files like CSS, JS, ...), implemented only for ZIMs in v1, list of top 50 stored in DB, absolute value and percentage available
| ContentUsageDuration | 2003 | Duration during which a given content has been used, based on 10 minutes interval (i.e. a single activity during a 10 minutes interval is marking these 10 minutes as "active"), list of top 10 stored in DB list, absolute value and percentage available |
| OffspotUsageDuration | 2004 | Duration during which the offspot has been turned on, single value, absolute value and percentage of the whole period available |
| SharedFiles | 2005 | Number of files added to sharing service (EduPi for now) and number of files removed from this service, single value (two values indeed) |

**Comment by Popolechien** [comment]
Looks good to me. Thanks.

**Comment by rgaudin** [comment]
Looks conform to previous discussions:

- what's a resource in `2002`?
- `2005` is the only one that's not yet implemented right?

**Comment by benoit74** [comment]
In `2002`, a resource is basically a web page. Description could be maybe better with "Number of visits per content objects (typically a web page), ignoring assets (images, technical files like CSS, JS, ...), implemented only for ZIMs in v1, list of top 50 stored in DB, absolute value and percentage available". Is it clearer?

`2001` and `2002` are mostly ready, only basic review is needed. Others have to be implemented.

**Comment by benoit74** [comment]
Oh, and I must stop to speak about `ContentObject` and use `ContentItem` instead

**Comment by benoit74** [comment]
I revisited the table to align names with the ones we have almost decided to use for UI + I have made the value stored in DB more explicit and I fixed some mistakes (e.g. we need to store the total number of visits and the total usage, so there is no need to store the percentage)

| Name | Unique ID | Definition | Value stored in DB for each aggregation | 
|----------|----------|----------|----------|
| PackagePopularity | 2001 | Number of visits of each package home pages | List of top 10 packages (with number of visits for each of them) + total number of visits  |
| PopularPages | 2002 | Number of visits per package objects (typically a web page), ignoring assets (images, technical files like CSS, JS, ...), implemented only for ZIMs in v1 | List of top 50 pages (package + page name, with number of visits for each of them) + total number of visits |
| AverageUsage | 2003 | Duration during which a given package has been used, based on 10 minutes interval (i.e. a single activity during a 10 minutes interval is marking these 10 minutes as "active") | List of top 10 packages (with usage - in minutes - for each of them) + total usage in minutes |
| Uptime | 2004 | Duration during which the offspot has been turned on | Single value, in minutes |
| SharedFiles | 2005 | Number of files added to sharing service (EduPi for now) and number of files removed from this service | Two values: number of files added + removed |

I think the name `AverageUsage` is not perfect. `PackageUsage` would probably be a bit better but it is a repetition of `PackagePopularity`, so we wanted to avoid this with Christina. Suggestions are welcomed.

We will meet on-site with Stephane and Christina on Tuesday (7th Nov) to discuss about UI, so we might make some adjustments at that point. Please speak-up before Tuesday if something is not ok for you. I will hopefully make this list definitive for v1 on Tuesday. UI will probably not yet be definitive at that point, but at least we must have a final agreement on KPIs.

Once this is OK, I will create sub-issues for each KPI implementation so that it will be easier to track / review one by one.

**Comment by benoit74** [comment]
We have agreed with Stephane that `AverageUsage` will indeed be named `TotalUsage`

Subtasks have been created for the backend part:
- https://github.com/offspot/metrics/issues/32
- https://github.com/offspot/metrics/issues/33
- https://github.com/offspot/metrics/issues/34
- https://github.com/offspot/metrics/issues/29
- https://github.com/offspot/metrics/issues/27

UI is still under discussion in [the specific ticket ](https://github.com/offspot/metrics/issues/9) and in live discussion.

I close this issue as it is now completed AFAIK.
